# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build client
      run: go build -v -o client ./client/client.go
      
    - name: Build server
      run: go build -v -o server ./server/server.go
      
    - name: Build malware
      run: env GOOS=windows GOARCH=amd64 go build -v -o basicKitten ./kitten/basicKitten/basicKitten.go
